### ISSUE TITLE
Создать в проекте папку src и разместить в ней стандартный  Angular проект

### ISSUE THREAD

**Issue by SashnikovNA** [natlex/City_past_frontend#1]
https://angular.io/start

Создать дефолтный Angular проект и pull request c его структурой в папку репозитория

**Comment by artfulsage** [comment]
@SashnikovNA я бы предложил вместо frontend назвать src, раз мы решили разделить репозитории.

**Comment by SashnikovNA** [comment]
поддерживаю

**Comment by alexevnaa** [comment]
Пулл реквест создан: https://github.com/natlex/City_past_frontend/pull/7

**Comment by alexevnaa** [comment]
Создала пулл реквест: https://github.com/natlex/City_past_frontend/pull/7

@artfulsage перекинуто в ревью
