### ISSUE TITLE
Описать групповые правила форматирования кода внутри Web Storm

### ISSUE THREAD

**Issue by SashnikovNA** [natlex/City_past_frontend#19]

**Comment by artfulsage** [comment]
@oyikagawa @SashnikovNA возможно, эта задача потеряла смысл. Разве что, как и в vscode, в Web Storm есть опция с форматтером по умолчанию, и нужно только ее поставить на prettier. Остальное должно решаться установленными плагинами eslint и prettier

**Comment by oyikagawa** [comment]
@artfulsage да, есть опция форматтера по умолчанию, поставил на prettier. Правда не знаю, насколько корректно все будет отрабатывать.

**Comment by artfulsage** [comment]
@oyikagawa пулл реквест сделаешь?
