### ISSUE TITLE
Figma - главная страница  + верстка header

### ISSUE THREAD

**Issue by SashnikovNA** [natlex/City_past_frontend#2]
- Изучить сходные порталы и подумать над основными сценариями поведения пользователей на портале

- создать макет основной страницы портала (можно использовать элементы angular material
https://material.angular.io/ ) и согласовать с командой

**Comment by SashnikovNA** [comment]
@alexevnaa  приложи тут в комментариях ссылку на  макет фигма плиз

**Comment by SashnikovNA** [comment]
https://www.figma.com/community/file/778763161265841481
Саша предложил на встрече

**Comment by alexevnaa** [comment]
Ссылка на макет https://www.figma.com/file/kwhDyjL3t4zafohMpxqs3S/Untitled?node-id=0%3A1
